### DISCUSSION TITLE
docke模式下,并且挂载目录为exFAT的硬盘无法创建{._文件名} 导致web页面报错

### DISCUSSION THREAD

**Discussion by captainstdin** [AlistGo/docs#278] [General]
failed get objs: failed to list objs: lstat /Volumes/1T/alist/admin/._cod13-无线战争-太空站.zip: operation not permitted

```
version: "2.1"
services:
  transmission:
    image: xhofe/alist:main
    container_name: alist
      #environment:
      #- PUID=1000
      #- PGID=1000
      #- TZ=Etc/UTC
    volumes:
      - $PWD/home/:/home
      - /Volumes/1T/alist/:/Volumes/1T/alist/
      - $PWD/etc/:/opt/alist/data
    ports:
      - 5244:5244
    restart: always
```
