### DISCUSSION TITLE
zh/config/other

### DISCUSSION THREAD

**Discussion by giscus** [AlistGo/docs#35] [Announcements]
# zh/config/other

AList v3的文档

https://alist.nn.ci/zh/config/other.html

**Comment by pikachullk** [comment]
我用的docker版本~好像没要求在同一台服务器啊~请教下现在是否还是需要再同一台服务器上？或者同一个局域网下也OK

**Reply by pikachullk** [reply]
实测同一局域网内的不同容器是可以的

**Reply by icedog111** [reply]
请问是如何实现的，我在一个局域网下使用离线下载，结果在Aria2中显示下载的文件存在Alist的TEMP文件夹中，而且没有权限，存储不成功，应该如何操作。

**Comment by Mosazh** [comment]
请问下载完成后文件移动失败是什么原因？不支持移动到中文文件夹吗？

**Comment by yws112358** [comment]
如果是在宿主系统安装的aria2  可以使用宿主机相对容器的网关ip去访问 一般是172.17.0.1的  。即http://172.17.0.1:6800/jsonrpc。后面是rpc-secret 密码  这样感觉网络相对稳定。

**Reply by pikachullk** [reply]
我用了macvlan…直接用主路由分配的ip～也稳的～感觉会不会不同的宿主机也可以

**Reply by yws112358** [reply]
transfer /opt/alist/data/temp/aria2/d31043df-f74b-4b31-85af-00ae3212a5b7/QQ9.6.8.28823.exe to [/家庭存储](/mnt/sda1)
错误
下载没问题，转移存储报错  不知道日志在哪查看

**Comment by tifa2007** [comment]
我的aria2设置的是https模式 若关掉http://172.17.0.1:6800/jsonrpc 可以进去但是AriaNg 就进不去。。反之同样道理，咋整？

**Comment by weigeloveu** [comment]
我这边在单独的网盘界面设置可以连接上aria2,但是设置里边的连接不上.
aria2ng也是可以正常连接的,alist aria2都是容器部署的.aria2用的是p3terx的aria2 pro

**Reply by weigeloveu** [reply]
Mac上安装,容器用的都是bridge

**Reply by mulberryS** [reply]
防火墙开放6800端口

**Comment by laxuou** [comment]
希望aria2之后可以支持rss订阅下载，到某个东西rss订阅时间到了就实行自动下载新的订阅，并且下载地址可自定

**Reply by pikachullk** [reply]
flexget好像是支持aria2的

**Comment by xzxiaoshan** [comment]
## 另外要保证两个程序是同一个用户运行，否则会出现 data/temp 目录中的临时文件无能被删除导致磁盘持续占用问题。

**Comment by laxtiz** [comment]
给大家提供一个方案

## 准备工作

创建一个当前用户可写目录

```bash
sudo mkdir -p /mnt/storage/downloads
sudo chown 1000:1000 /mnt/storage/downloads
```

## 部署

docker-compose.yml

```yaml
version: '3'

services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
    ports:
      - 5244:5244
    volumes:
      # alist 配置目录，与aria2 共享
      - /opt/alist/data:/opt/alist/data
      - /mnt:/mnt
    restart: always
  aria2:
    image: p3terx/aria2-pro:latest
    container_name: aria2
    environment:
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=HERE_IS_YOUR_SECRET
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - IPV6_MODE=false
    ports:
      - 6800:6800
      - 6888:6888
    volumes:
      - /opt/aria2/config:/config
      # aria2 默认下载目录
      - /mnt/storage/downloads:/downloads
      # 一定要和上面相同
      - /opt/alist/data:/opt/alist/data
    restart: always
```

进 alist 将 `/mnt/storage/downloads` 挂载为本地存储，这样既可以用Aria2 相关插件/程序下载下载，也支持 Alist 远程下载上传

**Reply by laxtiz** [reply]
补充一下，Alist 设置 Aria2 RPC 链接地址是 `http://aria2:6800/jsonrpc`，直接在 docker 同一子网下通讯。
外部使用Aria2 的话，用 ws://HOST_IP:6800/jsonrpc，或者自行架设反向代理nginx/traefik 之类的。

**Reply by weigeloveu** [reply]
感谢大佬指点,这样确实是在程序连接成功了,试着发送了几个任务到aria2,弹出来的通知是发送成功.但是这边依然是空的
<img width="619" alt="截屏2023-01-20 上午8 19 23" src="https://user-images.githubusercontent.com/19830500/213590749-ec615276-bdde-4516-a1f8-5b62d987fbc2.png">

**Reply by laxtiz** [reply]
你用AriaNG链接Aria2 RPC看看，或者看看 aria2 容器的日志，也许是下载出现问题了，我这边部署没问题的。
![Screenshot_2023-01-20-08-33-32-813_com.android.chrome.jpg](https://user-images.githubusercontent.com/3883767/213592613-19032537-c9f1-4e10-8f8b-d1f6569ecb10.jpg)

**Reply by weigeloveu** [reply]
aria2ng的任务里边也全是空的,日志也是空的.“设置-其他”跟“本地设置”里边都指向的http://aria2:6800/jsonrpc
刚才测试了一下,下载“文件夹”弹出的是发送成功,实际上并没有发送.下载“单文件”直接报错.
`Failed to send to aria2: AxiosError: Network Error`

**Reply by laxtiz** [reply]
下载“文件夹”是什么意思？
后台设置aria2是“离线下载”时调用的啊

**Reply by laxtiz** [reply]
前台本地下载的设置是你浏览器调用的，需要你浏览器所在的主机能访问的aria2 rpc地址，不然怎么叫“本地下载”

**Reply by weigeloveu** [reply]
比如说这样:
<img width="1161" alt="截屏2023-01-20 上午9 05 39" src="https://user-images.githubusercontent.com/19830500/213596094-5fc3ba7e-530f-4d6e-98ad-68d0b1597f06.png">

**Reply by weigeloveu** [reply]
我的compose您看一下
```
version: "3.8"

services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=022
    ports:
      - 5244:5244
    volumes:
      # alist 配置目录，与aria2 共享
      - /volume1/docker/alist:/opt/alist/data
      - /volume3/downloads:/mnt
#    network_mode: host
    restart: always
  aria2:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=1026
      - PGID=100
      - UMASK_SET=022
      - RPC_SECRET=略
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=true
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=略
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/aria2/config:/config
      - /volume3/downloads:/downloads
      - /volume1/docker/alist:/opt/alist/data
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
    #network_mode: host
#    network_mode: bridge
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
#    network_mode: host
#    network_mode: bridge
    ports:
      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
```
